name: MacOS
on:
    push:
        branches-ignore:
            - "releases/**"
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "**/ubuntu.yml"
            - "**/windows.yml"
    pull_request:
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "**/ubuntu.yml"
            - "**/windows.yml"
jobs:
    build:
        name: Build
        runs-on: macos-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                brew install x86_64-elf-gcc nasm
            - name: Build
              run: |
                  cmake \
                    -DCMAKE_C_COMPILER=x86_64-elf-gcc \
                    -DCMAKE_AR=x86_64-elf-gas \
                    -DCMAKE_LINKER=x86_64-elf-ld \
                    -DCMAKE_OBJCOPY=x86_64-elf-objcopy \
                    -DCMAKE_OBJDUMP=x86_64-elf-objdump \
                    -DCMAKE_RANLIB=x86_64-elf-ranlib \
                    -DCMAKE_ASM_COMPILER=/usr/local/bin/nasm \
                    -DCMAKE_SYSTEM_NAME=Linux \
                    -B build
                  cmake --build build --parallel 2 --verbose
