name: MacOS
on:
    push:
        branches-ignore:
            - "releases/**"
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "**/ubuntu.yml"
            - "**/windows.yml"
    pull_request:
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "**/ubuntu.yml"
            - "**/windows.yml"
jobs:
    build:
        name: Build
        runs-on: macos-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                brew install nasm
            - name: Build
              env:
                CC: gcc-11
                CXX: g++-11
              run: |
                  cmake -DCMAKE_ASM_COMPILER=/usr/local/bin/nasm -B build
                  cmake --build build --parallel 2 --verbose
