name: MacOS
on:
    push:
        branches-ignore:
            - "releases/**"
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "**/ubuntu.yml"
            - "**/windows.yml"
    pull_request:
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "**/ubuntu.yml"
            - "**/windows.yml"
jobs:
    build:
        name: Build
        runs-on: macos-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                brew install x86_64-elf-gcc nasm
            - name: Build
              env:
                TOOLPREFIX: x86_64-elf- 
                CC: x86_64-elf-gcc
                AS: x86_64-elf-gas
                LD: x86_64-elf-ld
                OBJCOPY: x86_64-elf-objcopy
                OBJDUMP: x86_64-elf-objdump
              run: |
                  cmake -DCMAKE_ASM_COMPILER=/usr/local/bin/nasm -B build
                  cmake --build build --parallel 2 --verbose
