name: Windows
on:
    push:
        branches-ignore:
            - "releases/**"
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "**/macos.yml"
            - "**/ubuntu.yml"
    pull_request:
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "**/macos.yml"
            - "**/ubuntu.yml"
jobs:
    test:
        name: Build
        runs-on: windows-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  choco install nasm
                  echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            - name: Set up GCC
              uses: egor-tensin/setup-gcc@v1
              with:
                  version: latest
                  platform: x32
            - name: Build
              run: |
                  cmake -B build
                  cmake --build build --parallel 2
