name: Windows
on:
    push:
        branches-ignore:
            - "releases/**"
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "macos.yml"
            - "ubuntu.yml"
    pull_request:
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "macos.yml"
            - "ubuntu.yml"
jobs:
    test:
        name: Build
        runs-on: windows-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  choco install nasm
            - name: Build
              run: |
                  cmake -B build
                  cmake --build build --parallel 2
